mybatis:
    mapper-locations: classpath:mapper/*xml
    configuration:
        map-underscore-to-camel-case: true
server:
    port: 8080
spring:
    freemarker:
        cache: false
        charset: utf-8
        expose-request-attributes: true
        expose-session-attributes: true
        suffix: .ftl
        template-loader-path: classpath:/templates/
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/babytun?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 12345678
    web:
        resources:
            static-locations: classpath:/static/